[package]
name = "cloudflare_ddns"
version = "0.1.0"
authors = ["Terrence Lam <skyuplam@gmail.com>"]

[dependencies]
trust-dns-resolver = "^0.8"
clap = "~2.30"
futures = "^0.1"
hyper = "^0.11"
hyper-tls = "^0.1"
tokio-core = "^0.1"
serde_json = "^1.0"
